server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://42.192.179.180:3306/train?useUnicode=true&characterEncoding=utf-8
    username: root
    password: pyc.0907
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 42.192.179.180
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0



  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.vernhe.springboot.project01.mapper: debug

